// AUTO-GENERATED by guests/build.rs — DO NOT EDIT MANUALLY
// This file is overwritten each time `cargo build` runs the guests crate.
// The placeholder value below will be replaced with the real ELF binary.

// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.20;

library Elf {
    bytes public constant PUZZLE_SOLVER_ELF = hex"00";
}
