// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// Generated by `cargo risczero build` — update when guest program changes.
// Image ID = SHA-256 of the guest ELF binary.

pragma solidity ^0.8.20;

library ImageID {
    bytes32 public constant PUZZLE_SOLVER_ID = 0x8da19e69de35e4e648d8ca7e6779069b50c09e9241ddd8cac6a6a199d0c7e8ed;
}
